######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 30 11:26:36 2007
######################################################################

TEMPLATE = app
TARGET = svg
DESTDIR = ./debug
OBJECTS_DIR = ./debug
#CONFIG += debug warn_on
CONFIG += release
INCLUDEPATH += include
QT += svg xml
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
HEADERS += debug.h 
SOURCES += main.cpp \
	debug.cpp 
